POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI1ZWQyNzZiMGJjZjRjNzgyMGJmNzFkMmIiLCJpYXQiOjE1OTEwMjU5MTB9.vCjmaUcAj1NSkdAfTtaYsKrtjrV5_Z57M1ekecCn0Rk

{
    "title": "Delete auth test",
    "author": "Juhana Kuparinen",
    "url": "http://localhost:3003/api/blogs",
    "likes": 0
}